swagger: '2.0'
info:
  description: API documentation for UserService
  version: 1.0.0
  title: User Service API
host: localhost:8000
basePath: /api/v1
schemes:
  - http
paths:
  /users:
    get:
      summary: Get all users
      description: Retrieve a list of all users
      responses:
        200:
          description: A list of users
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
    post:
      summary: Create a new user
      description: Add a new user to the system
      parameters:
        - in: body
          name: user
          description: User object to be created
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        201:
          description: User created successfully
          schema:
            $ref: '#/definitions/User'
  /users/{id}:
    get:
      summary: Get a user by ID
      description: Retrieve a single user by their ID
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: A single user
          schema:
            $ref: '#/definitions/User'
        404:
          description: User not found
    put:
      summary: Update a user
      description: Update an existing user
      parameters:
        - name: id
          in: path
          required: true
          type: integer
        - in: body
          name: user
          description: Updated user object
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: User updated successfully
          schema:
            $ref: '#/definitions/User'
        404:
          description: User not found
    delete:
      summary: Delete a user
      description: Remove a user from the system
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        204:
          description: User deleted successfully
        404:
          description: User not found
  /users/{id}/consumptions:
    get:
      summary: Get user consumptions by ID
      description: Retrieve a list of consumptions for a specific user by their ID
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          description: ID of the user
      responses:
        200:
          description: A list of consumptions for the user
          schema:
            type: array
            items:
              $ref: '#/definitions/Consumption'
        404:
          description: User not found

definitions:
  User:
    type: object
    required:
      - id
      - name
      - email
    properties:
      id:
        type: integer
        example: 1
      name:
        type: string
        example: 'John Doe'
      email:
        type: string
        example: 'john.doe@example.com'
  Consumption:
    type: object
    required:
      - id
      - userId
      - item
      - quantity
    properties:
      id:
        type: integer
        example: 1
      userId:
        type: integer
        example: 1
      item:
        type: string
        example: 'Apple'
      quantity:
        type: integer
        example: 3
