swagger: '2.0'
info:
  description: API documentation for ConsumptionService
  version: 1.0.0
  title: Consumption Service API
host: localhost:8002
basePath: /api/v1
schemes:
  - http
paths:
  /consumptions:
    get:
      summary: Get all consumptions
      description: Retrieve a list of all consumption records
      parameters:
        - name: user_id
          in: query
          required: false
          type: integer
          description: Filter consumptions by user ID
      responses:
        200:
          description: A list of consumption records
          schema:
            type: array
            items:
              $ref: '#/definitions/Consumption'
    post:
      summary: Create a new consumption record
      description: Add a new consumption record to the system
      parameters:
        - in: body
          name: consumption
          description: Consumption object to be created
          required: true
          schema:
            $ref: '#/definitions/Consumption'
      responses:
        201:
          description: Consumption record created successfully
          schema:
            $ref: '#/definitions/Consumption'
  /consumptions/{id}:
    get:
      summary: Get a consumption record by ID
      description: Retrieve a single consumption record by its ID
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: A single consumption record
          schema:
            $ref: '#/definitions/Consumption'
        404:
          description: Consumption record not found
    put:
      summary: Update a consumption record
      description: Update an existing consumption record
      parameters:
        - name: id
          in: path
          required: true
          type: integer
        - in: body
          name: consumption
          description: Updated consumption object
          required: true
          schema:
            $ref: '#/definitions/Consumption'
      responses:
        200:
          description: Consumption record updated successfully
          schema:
            $ref: '#/definitions/Consumption'
        404:
          description: Consumption record not found
    delete:
      summary: Delete a consumption record
      description: Remove a consumption record from the system
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        204:
          description: Consumption record deleted successfully
        404:
          description: Consumption record not found

definitions:
  Consumption:
    type: object
    required:
      - id
      - user_id
      - product_id
      - date
      - quantity
    properties:
      id:
        type: integer
        example: 1
      user_id:
        type: integer
        example: 1
      product_id:
        type: integer
        example: 1
      date:
        type: string
        format: date
        example: '2023-10-01'
      quantity:
        type: number
        example: 2.5
