swagger: '2.0'
info:
  description: API documentation for ProductService
  version: 1.0.0
  title: Product Service API
host: localhost:8001
basePath: /api/v1
schemes:
  - http
paths:
  /products:
    get:
      summary: Get all products
      description: Retrieve a list of all products
      responses:
        200:
          description: A list of products
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
    post:
      summary: Create a new product
      description: Add a new product to the inventory
      parameters:
        - in: body
          name: product
          description: Product object to be created
          required: true
          schema:
            $ref: '#/definitions/Product'
      responses:
        201:
          description: Product created successfully
          schema:
            $ref: '#/definitions/Product'

  /products/{id}:
    get:
      summary: Get a product by ID
      description: Retrieve a single product by its ID
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: A single product
          schema:
            $ref: '#/definitions/Product'
        404:
          description: Product not found
    put:
      summary: Update a product
      description: Update an existing product
      parameters:
        - name: id
          in: path
          required: true
          type: integer
        - in: body
          name: product
          description: Updated product object
          required: true
          schema:
            $ref: '#/definitions/Product'
      responses:
        200:
          description: Product updated successfully
          schema:
            $ref: '#/definitions/Product'
        404:
          description: Product not found
    delete:
      summary: Delete a product
      description: Remove a product from the inventory
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        204:
          description: Product deleted successfully
        404:
          description: Product not found

definitions:
  Product:
    type: object
    required:
      - id
      - name
      - description
      - sugar_intake
      - salt_intake
    properties:
      id:
        type: integer
        example: 1
      name:
        type: string
        example: 'Sugar'
      description:
        type: string
        example: 'A bag of sugar'
      sugar_intake:
        type: number
        format: float
        example: 1.99
      salt_intake:
        type: number
        format: float
        example: 0.5
